### PR TITLE
make tag customizable

### PR DESCRIPTION
**Pull request by pltchuong**
This would make each tag is customizable with default view as current designed

### CODE REVIEW

**Comment by AlexMordred** [comment]
@pltchuong I don't think this would work since the tag is inside a `v-for` loop. Have you tested it? Could you give me a real-life example?

**Comment by Cryde** [comment]
That's what I was looking for !  
A real life example would be to "change" de displaying of the tag 
For instance user type "mytag" and it display "#mytag"

**Comment by Cryde** [comment]
I have tested it : 
```

                                        <tags-input
                                                class="form-control"
                                                style="padding-top:4px"
                                                :add-tags-on-blur="true"
                                                placeholder="todo"
                                                element-id="tags"
                                        >
                                            <template v-slot:tag="tag">
                                                #{{ tag.tag.value }}
                                            </template>
                                        </tags-input>
```
It work very well :)

**Comment by AlexMordred** [comment]
Thanks guys and sorry for the late reaction. I merged #104 instead.

**Pull request closed without merging**
