### PR TITLE
Fix: Backspace and key event browser support

### PR DESCRIPTION
**Pull request by AWulkan**
Great work on the plugin, it's really good.

This pull request should fix the backspace problem, since Vue actually uses the `.delete` modifier, not `.backspace`.
https://vuejs.org/v2/guide/events.html#Key-Modifiers

It should also make the key events work in Chrome and Edge. I was having problems there until I changed from `keypress` to `keyup` and `keydown`.

I set the arrows keys to `keydown` so that you can just hold it down to scroll through available tags fast. Same with the delete key, if you want to delete all tags by just holding down backspace, instead och clicking several times. They still just trigger once if you don't hold it down. :)

### CODE REVIEW

**Comment by AlexMordred** [comment]
Thanks for your contribution!

The only problem I have with this is ".delete (captures both “Delete” and “Backspace” keys)" - that is why I didn't use it in the first place, as it's kind of counter-intuitive to delete tags by pressing "Delete" since tags are located on the left from the cursor.

Besides, `.backspace` works since Vue v.2.5.0 [](https://vuejs.org/v2/guide/events.html#Automatic-Key-Modifiers), and for older versions you can include this line `Vue.config.keyCodes.backspace = 8;`. Another option would be to use a key code as in `@keyup.8="..."` - seems like this would be a valid choice, what do you think?

**Comment by AWulkan** [comment]
Hey, thanks for the quick response.

The backspace doesn't work in Vue 2.5.13 for me. And when trying your demo in Chrome and Edge it doesn't work either, only for Firefox. Also, Visual Studio Code with "eslint-plugin-vue" complains that `.backspace` doesn't exist. I also can't find any documentation for it.

When pressing the del-button, the `.delete` only deletes tags if the input is already empty, which imo makes sense, but you got the final say on this matter.

As for the other keypress events, they wouldn't work for me in Edge or Chrome either, that's why I changed to keyup/keydown.

**Comment by AlexMordred** [comment]
Sorry, I failed to include the link about the backspace in my last response. I also get that error in vscode, but it works fine for me (although I'd only tested it in Firefox). Here is the link again [https://vuejs.org/v2/guide/events.html#Automatic-Key-Modifiers](https://vuejs.org/v2/guide/events.html#Automatic-Key-Modifiers).

Anyway, I've just tried `@keyup.8="removeLastTag"` in Firefox and Chromium in Ubuntu and it works fine. Could you please test it in your browsers and change the pull request to `@keyup.8` if that works? If it doesn't I'll just accept the current pull request with `.delete`.

**Comment by AWulkan** [comment]
I'll try `@keyup.8` tomorrow when I'm back at work, where I have everything set up. :)

On a sidenote, have you thought about providing the option to turn features like the backspace deletion off? For example, you could send `delete-on-backspace="false"` as a prop, which then prevents the event from running its method to delete a tag. This is not a super important feature, but I could see cases where you don't want backspace to trigger a deletion at all.

**Comment by AlexMordred** [comment]
Thanks :)

I've never thought about it. What would these cases be?

**Comment by AWulkan** [comment]
Simply to prevent accidential deletion of tags if you hit backspace one too many times. Since you can still delete all tags by clicking the 'X' icon on them, its not always necessary to also have the backspace delete functionality.

**Comment by AWulkan** [comment]
Tested `@keyup.8` and it works for Edge and Chrome on Windows 10 (don't have Firefox installed). If you said it works for Firefox on Ubuntu then I'm sure it's ok to merge with master.

**Comment by AlexMordred** [comment]
Thanks, appreciated! Seems like `@keyup.8` should work in older versions, doesn't say otherwise in the documentation. I'll merge your request and make a new release.

**Comment by AlexMordred** [comment]
Done. I've also implemented the feature you requested.

**Comment by AWulkan** [comment]
Great, just downloaded it and everything is working well. :)

**Pull request merged**
