### PR TITLE
Allow adding css classes to tags

### PR DESCRIPTION
**Pull request by gvlasov**
This change allows property `class` on tags and adds that class to tags if present:

```js
data() {
  return {
    existingTags: [
      {text: 'Hello', value: 'hello', class: 'greeting'},
      {text: 'Fork', value: 'fork', class: 'weapon'},
      {text: 'Some dude', value: 'some dude'}, // Class not requred, and classless tags can be mixed with classy ones
    ];
  }
}
```

Same class will be used on the tag in typeahead as on the selected tag, but they can be styled differently (see the code example below).

<details><summary>Example component code</summary>

```vue
<template>
    <tags-input
            :typeahead="true"
            :existing-tags="existingTags"
            :typeahead-hide-discard="true"
            :only-existing-tags="true"
            :typeahead-activation-threshold="0"
            class="root"
    />
</template>

<script>
    import VoerroTagsInput from '@voerro/vue-tagsinput';

    export default {
        name: "CustomTagsInput",
        data() {
            return {
                existingTags:
                    [
                        {text: 'Hello', value: 'hello', class: 'greeting'},
                        {text: 'Hola', value: 'hola', class: 'greeting'},
                        {text: 'Fork', value: 'fork', class: 'weapon'},
                        {text: 'Spork', value: 'spork', class: 'weapon'},
                        {text: 'Some dude', value: 'some dude'},
                    ]
            };
        },
        components: {
            'tags-input': VoerroTagsInput,
        }
    }
</script>

<style scoped>
    @import "~@voerro/vue-tagsinput/dist/style.css";

    .root >>> .typeahead-badges .tags-input-badge.greeting {
        background-color: #ff8181 !important;
    }

    .root >>> .typeahead-badges .tags-input-badge.weapon {
        background-color: #83ff83 !important;
    }

    .root >>> .tags-input .tags-input-badge.greeting {
        background-color: #8888ff !important;
    }

    .root >>> .tags-input .tags-input-badge.weapon {
        background-color: #ffff84 !important;
    }

</style>
```

</details>

Result:

### CODE REVIEW

**Comment by AlexMordred** [comment]
Thanks!

**Comment by AlexMordred** [comment]
Actually, reverted this. Seemed a bit odd applying the same class to both selected tags and typeahead badges since those have different styles originally.

**Comment by gvlasov** [comment]
@AlexMordred You have a better suggestion that would allow styling groups of badges?

**Comment by AlexMordred** [comment]
@gvlasov different classes can be applied to badges only thanks to your #104 solution. The default typeahead and default selected tags styles are different, have different font colors etc., so we probably shouldn't apply same classes to both. The typeahead also has a "dropdown" mode which this PR doesn't touch and I don't know if it should.

**Pull request merged**
